---
# tasks file for apache

- name: Install Apache web server for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install Apache web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
