---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: install httpd server
    yum:
      name: httpd
      state: present
    when: ansible_facts['os_family']|lower == 'redhat'

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_facts['os_family']|lower == 'redhat'

  - name: install apache2 server
    yum:
      name: apache2
      state: present
    when: ansible_facts['os_family']|lower == 'debian'

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_facts['os_family']|lower == 'debian'

  - name: copy index file
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0755
